name: Java CI with Maven

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    needs: mysql-setup  # Add a dependency on the mysql-setup job

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_USER: root
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: todoDB
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Wait for MySQL to be ready
        run: sleep 20s  # Adjust the sleep time based on your needs
      - name: Run tests
        run: mvn -B test --file pom.xml
      - name: Build with Maven
        run: mvn -B package --file pom.xml

  mysql-setup:
    runs-on: ubuntu-latest
    steps:
      - name: Set up MySQL
        uses: mirromutth/mysql-action@v1.1
        with:
          host port: 3306
          container port: 3306
          mysql version: '8.0'
          mysql database: 'todoDB'
          mysql root password: root
          mysql user: root
          mysql password: root

  publish-job:
    runs-on: ubuntu-latest
    needs: [build, mysql-setup]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - run: mvn --batch-mode --update-snapshots verify
      - run: mkdir staging && cp target/*.jar staging
      - uses: actions/upload-artifact@v3
        with:
          name: Package
          path: staging

